language: java
sudo: required

script: mvn test -B

services:
  - docker

before_install:
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/

script:
  - docker build -t $DOCKER_USER/k8s-spring .

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag back $DOCKER_USER/k8s-spring:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/k8s-spring:$TRAVIS_BUILD_NUMBER
  - docker tag back $DOCKER_USER/k8s-spring:latest
  - docker push $DOCKER_USER/k8s-spring:latest
  - kubectl version  --short


